### ISSUE TITLE
Stop Proof-of-Work, found a block, restart PoW for same block

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#633] opened 2016-10-03 13:00 UTC
With 0.31.2b4, the node says it found a block, stop computing then restart computing for same block:

``` bash
2016-10-03T14:56:18+02:00 - info: Matched 3 zeros 000E7AF5F0136B1EB8BE2489120F79AF212C636D28A3D705B1E8AA9B76263AA8 with Nonce = 300000022159 for block#43796 by J78bPU
2016-10-03T14:56:20+02:00 - info: Matched 4 zeros 000011E6210FBBA5C29B3A2A1E441F96E15B90C52CF2BCFCA61BA1C6CC7049CD with Nonce = 200000022372 for block#43796 by J78bPU
2016-10-03T14:56:20+02:00 - info: ENGINE #2 HAS FOUND A PROOF
2016-10-03T14:56:20+02:00 - info: Stop proof-of-work worker #1
2016-10-03T14:56:20+02:00 - info: Stop proof-of-work worker #2
2016-10-03T14:56:20+02:00 - info: Stop proof-of-work worker #3
2016-10-03T14:56:20+02:00 - info: Stop proof-of-work worker #4
2016-10-03T14:56:29+02:00 - info: Matched 3 zeros 00055526F96F701D5BB556364C649C445A98BA3EFBD5C477D1F15488A10992AA with Nonce = 100000001270 for block#43796 by J78bPU
2016-10-03T14:56:30+02:00 - info: Matched 3 zeros 0007CC74E645AFF316DAD86AF23CAED05B645DB4AD9615BFF87972D0C005226E with Nonce = 300000001406 for block#43796 by J78bPU
2016-10-03T14:56:32+02:00 - info: Node BSmbyQ (peer.duniter.org:8999) is UP!
2016-10-03T14:56:43+02:00 - info: Matched 3 zeros 0002C0544EAA8EB3F88252D969D7212BBF2FA4AF9D30B7B5B4F2CBA4A30FF76C with Nonce = 100000003045 for block#43796 by J78bPU
2016-10-03T14:56:49+02:00 - info: Matched 3 zeros 000197105D6144D9828992D6E2D9BA281417C11D77A0EDF25386C544D21B60B0 with Nonce = 300000003945 for block#43796 by J78bPU
2016-10-03T14:56:58+02:00 - info: Matched 3 zeros 000571568704BE2446F59E62B0C94B38129EB2312D5DB76F1FC26671657A2452 with Nonce = 300000004981 for block#43796 by J78bPU
2016-10-03T14:56:59+02:00 - info: Matched 3 zeros 000DE80A8425A1EB852D6B6C54DB0153B8D4B3C4FC73ABEBE1A06548BD13DF09 with Nonce = 100000004992 for block#43796 by J78bPU
2016-10-03T14:57:20+02:00 - info: Matched 3 zeros 00091702C14BC9862AF58ECE45FCA34D93A0F7BBA492052751BCD4901DD8FD70 with Nonce = 100000007646 for block#43796 by J78bPU
```

**Comment by M5oul** [comment] 2016-10-03 14:43
Strange, a valid match was found, but nothing happen, and the node continue computing and found an other valid block: :smile: 
```bash
2016-10-03T16:32:07+02:00 - info: Matched 3 zeros 000797E54E54A029B2DCCBBC00B2CAA8EACDFCC9585F8770E4D9A42276013D77 with Nonce = 400000001465 for block#43824 by J78bPU
2016-10-03T16:32:27+02:00 - info: Matched 3 zeros 000916D5678DDC9F1D666743B513F2B729847AA29E3F1EFA48FA8D4C0A079D21 with Nonce = 100000002948 for block#43824 by J78bPU
2016-10-03T16:33:03+02:00 - info: POST Peer BSmbyQCeRx#43821
2016-10-03T16:33:06+02:00 - info: Matched 4 zeros 00001B0EF07433644A7547519255CA79F2CB9188A36D46C7F87AC2300C37CBF6 with Nonce = 100000005858 for block#43824 by J78bPU
2016-10-03T16:33:06+02:00 - info: ENGINE #1 HAS FOUND A PROOF
2016-10-03T16:33:06+02:00 - info: Stop proof-of-work worker #1
2016-10-03T16:33:06+02:00 - info: Stop proof-of-work worker #2
2016-10-03T16:33:06+02:00 - info: Stop proof-of-work worker #3
2016-10-03T16:33:06+02:00 - info: Stop proof-of-work worker #4
2016-10-03T16:33:10+02:00 - info: Matched 3 zeros 0001F940C1E90803C9265F1E4D8C8AA57F89A2BC2EB91B0FC582136751877EF0 with Nonce = 100000000788 for block#43824 by J78bPU
2016-10-03T16:33:14+02:00 - info: POST Peer J78bPUvLjx#43793
2016-10-03T16:33:14+02:00 - info: POST Peer J78bPUvLjx#43793
2016-10-03T16:33:17+02:00 - info: Matched 3 zeros 000B0B1B88A05764A765DE98864332FAFFE8D81FFA64BF179094BF9AFA8578FC with Nonce = 400000001633 for block#43824 by J78bPU
2016-10-03T16:33:24+02:00 - info: Matched 3 zeros 00084A13AE70BC578A55725A8842F940C93883E0387168C1B00B7CA75CFC5581 with Nonce = 200000002440 for block#43824 by J78bPU
2016-10-03T16:33:24+02:00 - info: Matched 3 zeros 000FBF3197274E79316C9C6AE95E0D9E901DFDD53F4A263CC87A0CC923200154 with Nonce = 300000002590 for block#43824 by J78bPU
2016-10-03T16:33:25+02:00 - info: Matched 3 zeros 000A466A0E16140AF363441DFB03FBC81E95C11146DD46279EB7285EA799EE5A with Nonce = 300000002711 for block#43824 by J78bPU
2016-10-03T16:33:30+02:00 - info: POST Peer 2GF9YTSMdF#43793
2016-10-03T16:33:31+02:00 - info: Matched 3 zeros 000922505BB8A93E4D044CD7A190FB5E20B1BB0A7EB67C16E39268DA79840F21 with Nonce = 300000003419 for block#43824 by J78bPU
2016-10-03T16:33:35+02:00 - info: POST Peer BR5DDeKff8#43821
2016-10-03T16:33:36+02:00 - info: Matched 3 zeros 000D86FF737A0AAC30E9CD8846B7CD06AC2DD67CDA11356281184AEB2B20C46C with Nonce = 200000003963 for block#43824 by J78bPU
2016-10-03T16:33:37+02:00 - info: Matched 4 zeros 00002176B0EFBA79157AFAB2191622D5009D9A7C09143B602CC133E6C8965AAB with Nonce = 100000004160 for block#43824 by J78bPU
2016-10-03T16:33:37+02:00 - info: ENGINE #1 HAS FOUND A PROOF
2016-10-03T16:33:37+02:00 - info: Done: 00002176B0EFBA79157AFAB2191622D5009D9A7C09143B602CC133E6C8965AAB in 104.45s (4159 tests, ~39.82 tests/s)
2016-10-03T16:33:37+02:00 - info: FOUND proof-of-work with 4 leading zeros followed by [0-2]!
2016-10-03T16:33:37+02:00 - info: Stop proof-of-work worker #1
2016-10-03T16:33:37+02:00 - info: Stop proof-of-work worker #2
2016-10-03T16:33:37+02:00 - info: Stop proof-of-work worker #3
2016-10-03T16:33:37+02:00 - info: Stop proof-of-work worker #4
2016-10-03T16:33:37+02:00 - info: Matched 3 zeros 0002FB3250084A6650A37F9E0E23A96B74C3476A7EFC27F797CC093787737871 with Nonce = 400000004183 for block#43824 by J78bPU
2016-10-03T16:33:37+02:00 - info: Block #43824 added to the blockchain in 243 ms
2016-10-03T16:33:37+02:00 - info: POST Block block#43824
2016-10-03T16:33:37+02:00 - info: Done: 00002176B0EFBA79157AFAB2191622D5009D9A7C09143B602CC133E6C8965AAB in 104.92s (4159 tests, ~39.64 tests/s)
```

**Comment by c-geek** [comment] 2016-10-03 15:10
That's really weird, indeed. Thanks for having noticed it.

I will wait a bit to also generates the situation on my side, since this is not a blocking issue yet. But we need to fix this for middle/long term as this generates a security isue.

**Comment by M5oul** [comment] 2016-10-03 20:59
Looking at all generated blocks from my node, it's displayed two times since this first time on logs:
```bash
2016-09-30T22:54:55+02:00 - info: Done: 00000116F2B661678C9EEB34A87752FEF8C03662F0B6F62D66827EFE74DE822A in 473.96s (14968 tests, ~31.58 tests/s)
2016-09-30T22:54:55+02:00 - info: Done: 00000116F2B661678C9EEB34A87752FEF8C03662F0B6F62D66827EFE74DE822A in 473.87s (14968 tests, ~31.59 tests/s)
```
Before 30 September, double match doesn't appear, but since this date there is almost ~5 blocks matched two times.

[0.31.2beta{1,2} was release 30 September](https://github.com/duniter/duniter/releases/tag/v0.31.2b1). May be linked to one of [this issues](https://github.com/duniter/duniter/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3AProof-of-Work%20is%3Aclosed%20milestone%3A0.31.2%20).

----

May be two core found same block same time. Does CPU cores try to found blocks with different `Nonce`?

```bash
2016-10-03T16:33:37+02:00 - info: Done: 00002176B0EFBA79157AFAB2191622D5009D9A7C09143B602CC133E6C8965AAB in 104.45s (4159 tests, ~39.82 tests/s)
2016-10-03T16:33:37+02:00 - info: Done: 00002176B0EFBA79157AFAB2191622D5009D9A7C09143B602CC133E6C8965AAB in 104.92s (4159 tests, ~39.64 tests/s)
2016-10-03T16:56:49+02:00 - info: Done: 00001DB3F7B7C0F5D51CDBA0F50757663F07C5443B31E61E5D1320125CC9AF95 in 98.11s (11305 tests, ~115.22 tests/s)
2016-10-03T18:52:23+02:00 - info: Done: 00000638F53A1B371FBACF074FF986F1C78053723FC66925361FE6E649C0291E in 481.42s (44504 tests, ~92.44 tests/s)
2016-10-03T20:01:15+02:00 - info: Done: 000004A85C0C5BBEADA1E525196A5B58A2935D93B822A26E625FAC83D1DB32CB in 844.72s (81229 tests, ~96.16 tests/s)
2016-10-03T20:34:37+02:00 - info: Done: 000002B3B38768BD385F764F1E8BB2CA987F83C953AE32582BB7099DEEABE71C in 426.44s (27431 tests, ~64.33 tests/s)
2016-10-03T21:52:25+02:00 - info: Done: 000004A66BB35EA150B2F00A0B6EB8C5D24649AFF742E7C786E47E370342C117 in 1190.97s (124051 tests, ~104.16 tests/s)
2016-10-03T22:24:17+02:00 - info: Done: 00000AC9F02304957ED936CDDE83EF2BC4EE4926F973E3821A27CB4AD9E7C81D in 837.12s (13587 tests, ~16.23 tests/s)
2016-10-03T22:24:18+02:00 - info: Done: 00000AC9F02304957ED936CDDE83EF2BC4EE4926F973E3821A27CB4AD9E7C81D in 837.57s (13587 tests, ~16.22 tests/s)
```

**Comment by c-geek** [comment] 2016-10-04 11:30
Yes, look at above logs: they say `Nonce = ...` and each Nonce starts with a 1, 2, 3 or 4 depending on the core number computing it.

**Comment by c-geek** [comment] 2017-01-02 15:33
I've rewritten the way proof-of-work engine dialogs with its thread. Hope it will be better this time, I close the issue for now, but do not hesitate to reopen it later on if you reproduce it.

**Comment by M5oul** [comment] 2017-02-01 09:43
I reproduced the bug many times on Ğtest:
```bash
2017-02-01T10:37:45+01:00 - info: Matched 3 zeros 0008A20762EC7D6DFE48C0DAD94ECA4CAEA2460268ADCAC43F53972BED9A255B with Nonce = 10400000002409 for block#2542 by J78bPU
2017-02-01T10:38:10+01:00 - info: Matched 4 zeros 00003DAFA49B59CD1A4DDB31FA90761467F31BD424E6A7820A9BCCFD18DA1CCF with Nonce = 10100000004678 for block#2542 by J78bPU
2017-02-01T10:38:10+01:00 - info: ENGINE #1 HAS FOUND A PROOF
2017-02-01T10:38:10+01:00 - info: Stop proof-of-work worker #1
2017-02-01T10:38:10+01:00 - info: Stop proof-of-work worker #2
2017-02-01T10:38:10+01:00 - info: Stop proof-of-work worker #3
2017-02-01T10:38:10+01:00 - info: Stop proof-of-work worker #4
2017-02-01T10:38:10+01:00 - info: Done: 00003DAFA49B59CD1A4DDB31FA90761467F31BD424E6A7820A9BCCFD18DA1CCF in 46.17s (4677 tests, ~101.29 tests/s)
2017-02-01T10:38:10+01:00 - info: FOUND proof-of-work with 4 leading zeros followed by [0-5]!
2017-02-01T10:38:10+01:00 - info: Generating proof-of-work with 4 leading zeros followed by [0-5]... (CPU usage set to 29%) for block#2542 J78bPU
2017-02-01T10:38:10+01:00 - info: Stop proof-of-work worker #1
2017-02-01T10:38:10+01:00 - info: Stop proof-of-work worker #2
2017-02-01T10:38:10+01:00 - info: Stop proof-of-work worker #3
2017-02-01T10:38:10+01:00 - info: Stop proof-of-work worker #4
2017-02-01T10:38:28+01:00 - info: Matched 3 zeros 0006A0C60FBB8A44911E2A1997647BB89832EA6B2B5B38E51B4ACD4157649FCE with Nonce = 10200000002051 for block#2542 by J78bPU
2017-02-01T10:38:28+01:00 - info: Pulling blocks from the network...
2017-02-01T10:38:29+01:00 - info: Will pull blocks from the network in 3 min 48 sec
2017-02-01T10:38:35+01:00 - info: Matched 3 zeros 0009095EF8F294D1E3CC32824CD07461C546A80FE706145E3157D3C08DA6E8EC with Nonce = 10200000002711 for block#2542 by J78bPU
2017-02-01T10:38:40+01:00 - info: POST Peer CSjgcGguFJ#2530
2017-02-01T10:38:40+01:00 - warn: getaddrinfo ENOTFOUND 2a01 2a01:8999
2017-02-01T10:38:40+01:00 - info: Peer CSjgcGguFJe3ghBBjjGyNVdvC3rqtXE7rSxUaLzjxBhR unreachable: now considered as DOWN.
2017-02-01T10:38:48+01:00 - info: Matched 4 zeros 0000D0CA486F8E957E6B1ADD212BA3C8DD642665A436DC29003DDBA2C1424F18 with Nonce = 10100000005761 for block#2542 by J78bPU
```

**Comment by c-geek** [comment] 2017-02-01 09:49
I put this bug to Horizon because it is very hard to figure out. Also it is not a blocking bug.

**Comment by Tortue95** [comment] 2017-02-27 14:22
the issue is here in the file /node_modules/duniter-prover/lib/permanentProver.js

```
const current = yield server.dal.getCurrentBlockOrNull();
const selfPubkey = server.keyPair.publicKey;
const block2 = yield generator.makeNextBlock();
const trial2 = yield server.getBcContext().getIssuerPersonalizedDifficulty(selfPubkey);
checkTrialIsNotTooHigh(trial2, current, selfPubkey);
lastComputedBlock = yield generator.makeNextBlock(block2, trial2);
```

2 time we do the makeNextBlock() i don't understend why...

on my node i pushed this code and is working well
```
const current = yield server.dal.getCurrentBlockOrNull();
const selfPubkey = server.keyPair.publicKey;
const trial2 = yield server.getBcContext().getIssuerPersonalizedDifficulty(selfPubkey);
checkTrialIsNotTooHigh(trial2, current, selfPubkey);
lastComputedBlock = yield generator.makeNextBlock();
```

**Comment by c-geek** [comment] 2017-02-27 14:31
How long time have you been testing this new code?

**Comment by Tortue95** [comment] 2017-02-27 14:33
heu 5 min ^^ just time to generate 1 block (with no transaction)

**Comment by c-geek** [comment] 2017-02-27 14:35
OK :) let's wait a bit then.

**Comment by Tortue95** [comment] 2017-02-27 14:48
it's seems to be working well, I just generated my 2de bloc with 1 transaction on it :)

**Comment by M5oul** [comment] 2017-02-27 18:52
I am trying this code to see If I reproduce this bug.

**Comment by M5oul** [comment] 2017-02-27 19:18
Bug reproduced:
```bash
2017-02-27T19:59:25+01:00 - info: Matched 5 zeros 0000085CCE4EAFC26FDD2562EC2051B60A304730623C356C8F7BC642DC73D52D with Nonce = 10300000017692 for block#9742 by J78bPU
2017-02-27T19:59:25+01:00 - info: ENGINE #3 HAS FOUND A PROOF
2017-02-27T19:59:25+01:00 - info: Stop proof-of-work worker #1
2017-02-27T19:59:25+01:00 - info: Stop proof-of-work worker #2
2017-02-27T19:59:25+01:00 - info: Stop proof-of-work worker #3
2017-02-27T19:59:25+01:00 - info: Stop proof-of-work worker #4
2017-02-27T19:59:26+01:00 - info: Done: 0000085CCE4EAFC26FDD2562EC2051B60A304730623C356C8F7BC642DC73D52D in 290.34s (17691 tests, ~60.93 tests/s)
2017-02-27T19:59:26+01:00 - info: FOUND proof-of-work with 4 leading zeros followed by [0-3]!
2017-02-27T19:59:26+01:00 - info: Generating proof-of-work with 4 leading zeros followed by [0-3]... (CPU usage set to 29%) for block#9742 J78bPU
2017-02-27T19:59:26+01:00 - info: Stop proof-of-work worker #1
2017-02-27T19:59:26+01:00 - info: Stop proof-of-work worker #2
2017-02-27T19:59:26+01:00 - info: Stop proof-of-work worker #3
2017-02-27T19:59:26+01:00 - info: Stop proof-of-work worker #4
2017-02-27T19:59:38+01:00 - info: Pulling blocks from the network...
2017-02-27T19:59:38+01:00 - info: Peer 8KTEFQS78HwEz1NK627rNsYwENxNXJyvtyMAyfKPXZRB unreachable: now considered as DOWN.
2017-02-27T19:59:39+01:00 - info: Will pull blocks from the network in 1 min 6 sec
2017-02-27T19:59:41+01:00 - info: Matched 3 zeros 00098CF18FFDA1B1F52B1350CB439D6E64A9B49F6080FC845AD304937B8A16F1 with Nonce = 10100000001045 for block#9742 by J78bPU
2017-02-27T19:59:48+01:00 - warn: Pulling not finished after 10000 ms, restart PoW
```

May I had to restart the node to take into account the patch?

**Comment by Tortue95** [comment] 2017-02-27 19:30
yes, just restart the duniter node, to take effect

**Comment by M5oul** [comment] 2017-02-28 21:47
Ok, this patch doesn't work:

```bash
2017-02-28T22:46:01+01:00 - info: Matched 4 zeros 000011B986508B6030686D52733F7E28C646B239AFC41FE276996A428B140DAC with Nonce = 10100000006868 for block#9998 by J78bPU
2017-02-28T22:46:01+01:00 - info: ENGINE #1 HAS FOUND A PROOF
2017-02-28T22:46:01+01:00 - info: Stop proof-of-work worker #1
2017-02-28T22:46:01+01:00 - info: Stop proof-of-work worker #2
2017-02-28T22:46:01+01:00 - info: Stop proof-of-work worker #3
2017-02-28T22:46:01+01:00 - info: Stop proof-of-work worker #4
2017-02-28T22:46:01+01:00 - info: Done: #9998, 000011B986508B6030686D52733F7E28C646B239AFC41FE276996A428B140DAC in 115.27s (6867 tests, ~59.57 tests/s)
2017-02-28T22:46:01+01:00 - info: FOUND proof-of-work with 4 leading zeros followed by [0-7]!
2017-02-28T22:46:01+01:00 - info: Generating proof-of-work with 4 leading zeros followed by [0-7]... (CPU usage set to 29%) for block#9998 J78bPU
2017-02-28T22:46:01+01:00 - info: Stop proof-of-work worker #1
2017-02-28T22:46:01+01:00 - info: Stop proof-of-work worker #2
2017-02-28T22:46:01+01:00 - info: Stop proof-of-work worker #3
2017-02-28T22:46:01+01:00 - info: Stop proof-of-work worker #4
2017-02-28T22:46:21+01:00 - info: Pulling blocks from the network...
2017-02-28T22:46:23+01:00 - info: Will pull blocks from the network in 0 min 39 sec
2017-02-28T22:46:26+01:00 - info: POST Peer C4orqutdb3#9967
2017-02-28T22:46:26+01:00 - warn: Could not reach duniter.jadden.info:443
2017-02-28T22:46:28+01:00 - info: Matched 3 zeros 00025962A38244B760F0D56CAC16CF6AD80EC2AB8CB30DD0539072C1A7DCDB5A with Nonce = 10400000002448 for block#9998 by J78bPU
```

**Comment by Tortue95** [comment] 2017-03-01 12:35
curious, because it's working well for me,
i just put this code on the new version of duniter v0.90.9 and it's working too.

`2017-03-01T12:38:44+01:00 - info: GIVEN proof-of-work for block#10111 with 4 leading zeros followed by [0-9A]! stop PoW for 8marFc
2017-03-01T12:38:44+01:00 - warn: The proof-of-work generation was canceled: Proof-of-work computation canceled because block received
2017-03-01T12:38:44+01:00 - trace: PoW loops = 18
2017-03-01T12:38:45+01:00 - info: Generating proof-of-work with 4 leading zeros followed by [0-9A]... (CPU usage set to 90%) for block#10112 8marFc
2017-03-01T12:38:45+01:00 - info: Stop proof-of-work worker #1
2017-03-01T12:38:45+01:00 - info: Stop proof-of-work worker #2
2017-03-01T12:38:45+01:00 - info: Stop proof-of-work worker #3
2017-03-01T12:38:45+01:00 - info: Stop proof-of-work worker #4
2017-03-01T12:38:46+01:00 - info: Changing conf to: {"prefix":10} on engine#1
2017-03-01T12:38:46+01:00 - info: Changing conf to: {"prefix":10} on engine#2
2017-03-01T12:38:46+01:00 - info: Changing conf to: {"prefix":10} on engine#3
2017-03-01T12:38:46+01:00 - info: Changing conf to: {"prefix":10} on engine#4
2017-03-01T12:38:50+01:00 - warn: Pulling not finished after 10000 ms, restart PoW
2017-03-01T12:39:04+01:00 - info: Matched 4 zeros 0000C3DEBB3D62413CBD508E66EF21EA0705062D3304A65EE25F94C390050DBF with Nonce = 10300000000775 for block#10112 by 8marFc
2017-03-01T12:39:54+01:00 - info: Matched 3 zeros 0009F2A26E73FF6E3A4658E9B158ACA4037B73721206CEA745944811FEE5E8D6 with Nonce = 10400000002829 for block#10112 by 8marFc
2017-03-01T12:39:54+01:00 - info: Matched 3 zeros 00067C991C122E53EBE3CE5A3F298304EB541D3E21FF7CA7D7324C1661BD7556 with Nonce = 10300000002810 for block#10112 by 8marFc
2017-03-01T12:39:56+01:00 - info: Pulling blocks from the network...
2017-03-01T12:39:57+01:00 - info: Will pull blocks from the network in 1 min 20 sec
2017-03-01T12:40:06+01:00 - warn: Pulling not finished after 10000 ms, restart PoW
2017-03-01T12:41:15+01:00 - info: Matched 3 zeros 000EA3A12526788BF188B0FA118DAFF18CDC005C244B8A8FEF3ED2CBC51C39E7 with Nonce = 10200000006059 for block#10112 by 8marFc
2017-03-01T12:41:16+01:00 - info: Pulling blocks from the network...
2017-03-01T12:41:16+01:00 - trace: Try with duniter.jadden.info:443 2dVpDy
2017-03-01T12:41:16+01:00 - trace: Try with gtest.monnaielibreoccitanie.org:80 CpFjJM
2017-03-01T12:41:16+01:00 - trace: Try with 82.239.120.237:30398 CSjgcG
2017-03-01T12:41:16+01:00 - trace: Try with duniter.grohub.org:8999 bDq9H4
2017-03-01T12:41:17+01:00 - info: Will pull blocks from the network in 1 min 21 sec
2017-03-01T12:41:26+01:00 - warn: Pulling not finished after 10000 ms, restart PoW
2017-03-01T12:41:34+01:00 - info: Matched 3 zeros 000EA98339AEECDB34ED33E2FAC4D939CD0B48B70593690C8AE4D0D383428936 with Nonce = 10400000006919 for block#10112 by 8marFc
2017-03-01T12:41:36+01:00 - info: Matched 4 zeros 00002116BA9E6D1D18A3AA91DD0C72D208A55BF1598E9EEF338C8E0D06223ECC with Nonce = 10400000007010 for block#10112 by 8marFc
2017-03-01T12:41:36+01:00 - info: ENGINE #4 HAS FOUND A PROOF
2017-03-01T12:41:36+01:00 - info: Stop proof-of-work worker #1
2017-03-01T12:41:36+01:00 - info: Stop proof-of-work worker #2
2017-03-01T12:41:36+01:00 - info: Stop proof-of-work worker #3
2017-03-01T12:41:36+01:00 - info: Stop proof-of-work worker #4
2017-03-01T12:41:36+01:00 - info: Done: #10112, 00002116BA9E6D1D18A3AA91DD0C72D208A55BF1598E9EEF338C8E0D06223ECC in 171.84s (7009 tests, ~40.79 tests/s)
2017-03-01T12:41:36+01:00 - info: FOUND proof-of-work with 4 leading zeros followed by [0-9A]!
2017-03-01T12:41:38+01:00 - info: Block #10112 added to the blockchain in 1770 ms
2017-03-01T12:41:38+01:00 - trace: PoW loops = 19
2017-03-01T12:41:38+01:00 - warn: Too high difficulty: waiting for other members to write next block
2017-03-01T12:41:38+01:00 - info: POST Block block#10112`

**Comment by c-geek** [comment] 2017-03-03 10:45
Yes, @Tortue95`s code should be working. And it is the obvious fix as well: indeed we computed 2 times the same PoW for 1 block.

**Comment by c-geek** [comment] 2017-03-03 10:46
This will probably has an important impact on the difficulty level when this patch is deployed.

I'm testing it, but I think it is OK and will be part of next release.

**Comment by c-geek** [comment] 2017-03-03 16:03
Thank you very much to both of you @M5oul and @Tortue95, and good bug has been fixed!

**Closed by c-geek** 2017-03-03 16:03 UTC
Labels: bug, Proof-of-Work
