### ISSUE TITLE
Database not well cleared when reset database?

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#522] opened 2016-08-10 16:12 UTC
Using Duniter Desktop 0.22.0.
Following #521, I tried to resync, the were no choice of nodes to sync on, so, I reset database, then resync:
```bash
2016-08-10T18:02:55+02:00 - debug: Generating server's peering entry based on block#469...
2016-08-10T18:02:55+02:00 - debug: Document write error:  Signature from a peer must match
2016-08-10T18:05:03+02:00 - info: Checking UPnP features...
2016-08-10T18:05:05+02:00 - error: Error: timeout
    at Timeout._onTimeout (/home/moul/projects/duniter/sources/node_modules/nnupnp/lib/nat-upnp/client.js:178:14)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
2016-08-10T18:05:15+02:00 - info: Duniter server stop listening
2016-08-10T18:05:15+02:00 - info: Duniter server stop listening
2016-08-10T18:05:15+02:00 - info: Proof-of-work computation STOPPED.
2016-08-10T18:05:15+02:00 - debug: Soft data reset... [cache]
2016-08-10T18:05:15+02:00 - debug: Soft data reset... [data]
2016-08-10T18:05:27+02:00 - info: Try with duniter.fraslin.net:8999 9bZEAT
2016-08-10T18:05:27+02:00 - info: Sync started.
2016-08-10T18:05:27+02:00 - info: Downloading Blockchain...
2016-08-10T18:05:27+02:00 - info: Connecting to 149.202.57.140...
2016-08-10T18:05:27+02:00 - debug: dl starts from 3500
2016-08-10T18:05:27+02:00 - info: Getting chunck from 3500 to 4000
2016-08-10T18:05:34+02:00 - info: Downloaded 11%, Applied 0%
2016-08-10T18:05:34+02:00 - debug: dl starts from 4000
2016-08-10T18:05:34+02:00 - debug: apply starts from 3500
2016-08-10T18:05:34+02:00 - debug: Applying from 3500
2016-08-10T18:05:34+02:00 - debug: Peer 9bZEAT is on same blockchain
2016-08-10T18:05:34+02:00 - info: Getting chunck from 4000 to 4500
2016-08-10T18:05:34+02:00 - info: Cannot read property 'UDTime' of null
2016-08-10T18:05:34+02:00 - error: TypeError: Cannot read property 'UDTime' of null
    at /home/moul/projects/duniter/sources/app/service/BlockchainService.js:457:37
    at next (native)
    at onFulfilled (/home/moul/projects/duniter/sources/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)
2016-08-10T18:05:34+02:00 - warn: Cannot read property 'UDTime' of null
2016-08-10T18:05:34+02:00 - info: External access: 83.197.194.85:46608
2016-08-10T18:05:34+02:00 - debug: Generating server's peering entry based on block#0...
2016-08-10T18:05:34+02:00 - debug: Document write error:  Signature from a peer must match
2016-08-10T18:05:34+02:00 - error: TypeError: Cannot set property 'documentType' of undefined
    at /home/moul/projects/duniter/sources/app/service/PeeringService.js:281:27
    at next (native)
    at onFulfilled (/home/moul/projects/duniter/sources/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)
2016-08-10T18:05:34+02:00 - warn: Cannot set property 'documentType' of undefined
2016-08-10T18:05:41+02:00 - info: Downloaded 13%, Applied 0%
```
As you could see, the sync started at 11% to 13%, then stopped with an error:
`Cannot read property 'UDTime' of null`
It seems the database were not well cleared.

**Comment by c-geek** [comment] 2016-08-23 11:34
Hmmm that's a bit weird, I prefer to delay the fix to the next major release.

**Comment by c-geek** [comment] 2016-08-23 11:35
Maybe linked to #521, indeed.

**Comment by c-geek** [comment] 2016-09-19 15:34
Yes, but Galuel also encountered in #601, so it begins to be recurrent. I will have a look and put it to Horizon milestone if I really can't reproduce it.

**Comment by c-geek** [comment] 2016-09-22 17:20
I will see if I can make the reset *hard* again, that is, deleting the database files insteaf of *soft* reset which roughly makes a `DELETE * from ALL TABLES`.

**Comment by c-geek** [comment] 2016-09-26 08:07
I set this issue as duplicate of #601

**Closed by c-geek** 2016-09-26 08:07 UTC
Labels: bug
