### ISSUE TITLE
Node crashed

### ISSUE THREAD

**Issue by Insoleet** [duniter/duniter#482] opened 2016-06-18 07:47 UTC
We saw it during RML7, it happened again : 

```
2016-06-18T09:46:12+02:00 - error: ERROR >> UPDATE peer SET `version` = ?, `currency` = ?, `status` = ?, `statusTS` = ?, `hash` = ?, `first_down` = ?, `last_try` = ?, `pubkey` = ?, `block` = ?, `signature` = ?, `endpoints` = ?, `raw` = ? WHERE `pubkey` = ? [2,"test_net","DOWN",1465958832,"95945A2CBF7193F6547F362A5FB12E785C221BA0A20A509BDC0F5789E1C8B893",1465970953855,1466235972316,"BjY41NKqFZjZUprp6sZX2yuPdFKCCdKcFYp1SvVASZhV","14415-00002759C094E9AD6945352832A1E0774C5190D2CBAE02F23766EB74DCEAEC55","9hBdtUBLekHtsm/A+7HMHK+iaCec/bUc6Pjqit6cNik9boOUHf2dsueV7ffc7GYl5/MoowaFDRnCqsdKkBVfCQ==","[\"BASIC_MERKLED_API 192.168.1.18 2a01:e35:8ae7:8bb0:8c25:2a71:62b8:d2f0 9337\"]","Version: 2\nType: Peer\nCurrency: test_net\nPublicKey: BjY41NKqFZjZUprp6sZX2yuPdFKCCdKcFYp1SvVASZhV\nBlock: 14415-00002759C094E9AD6945352832A1E0774C5190D2CBAE02F23766EB74DCEAEC55\nEndpoints:\nBASIC_MERKLED_API 192.168.1.18 2a01:e35:8ae7:8bb0:8c25:2a71:62b8:d2f0 9337\n","BjY41NKqFZjZUprp6sZX2yuPdFKCCdKcFYp1SvVASZhV"] Error: SQLITE_READONLY: attempt to write a readonly database
    at Error (native)
2016-06-18T09:46:12+02:00 - error: ERROR >> UPDATE peer SET `version` = ?, `currency` = ?, `status` = ?, `statusTS` = ?, `hash` = ?, `first_down` = ?, `last_try` = ?, `pubkey` = ?, `block` = ?, `signature` = ?, `endpoints` = ?, `raw` = ? WHERE `pubkey` = ? [2,"test_net","DOWN",1465808792,"FAAAA8E5879E5D396722ED71E1D0989EECD7060A32D00BDF7D56E1BE28318897",1465820596460,1466235972320,"5ExBCM9a9DJSxtRgjkEoNxX3LvUVEeYsG6WZAbChGfn6","13964-00000256B471DF89AF59D4EAE519418C49B792082A2E5E18883CB25EC0A83C09","HjtlZWccKy8Jxh/Y9hfbeZgFIsmQ4z35osyIWKEtiRloPLK7hb1HIefLrIWsFC5X5mylB/UzQwMNCULzKy7zBA==","[\"BASIC_MERKLED_API 88.190.82.70 fe80::219:dbff:fede:da54 61582\"]","Version: 2\nType: Peer\nCurrency: test_net\nPublicKey: 5ExBCM9a9DJSxtRgjkEoNxX3LvUVEeYsG6WZAbChGfn6\nBlock: 13964-00000256B471DF89AF59D4EAE519418C49B792082A2E5E18883CB25EC0A83C09\nEndpoints:\nBASIC_MERKLED_API 88.190.82.70 fe80::219:dbff:fede:da54 61582\n","5ExBCM9a9DJSxtRgjkEoNxX3LvUVEeYsG6WZAbChGfn6"] Error: SQLITE_READONLY: attempt to write a readonly database
    at Error (native)
2016-06-18T09:46:12+02:00 - error: ERROR >> UPDATE peer SET `version` = ?, `currency` = ?, `status` = ?, `statusTS` = ?, `hash` = ?, `first_down` = ?, `last_try` = ?, `pubkey` = ?, `block` = ?, `signature` = ?, `endpoints` = ?, `raw` = ? WHERE `pubkey` = ? [2,"test_net","DOWN",1465808792,"FAAAA8E5879E5D396722ED71E1D0989EECD7060A32D00BDF7D56E1BE28318897",1465820596460,1466235972325,"5ExBCM9a9DJSxtRgjkEoNxX3LvUVEeYsG6WZAbChGfn6","13964-00000256B471DF89AF59D4EAE519418C49B792082A2E5E18883CB25EC0A83C09","HjtlZWccKy8Jxh/Y9hfbeZgFIsmQ4z35osyIWKEtiRloPLK7hb1HIefLrIWsFC5X5mylB/UzQwMNCULzKy7zBA==","[\"BASIC_MERKLED_API 88.190.82.70 fe80::219:dbff:fede:da54 61582\"]","Version: 2\nType: Peer\nCurrency: test_net\nPublicKey: 5ExBCM9a9DJSxtRgjkEoNxX3LvUVEeYsG6WZAbChGfn6\nBlock: 13964-00000256B471DF89AF59D4EAE519418C49B792082A2E5E18883CB25EC0A83C09\nEndpoints:\nBASIC_MERKLED_API 88.190.82.70 fe80::219:dbff:fede:da54 61582\n","5ExBCM9a9DJSxtRgjkEoNxX3LvUVEeYsG6WZAbChGfn6"] Error: SQLITE_READONLY: attempt to write a readonly database
    at Error (native)
2016-06-18T09:46:12+02:00 - error: ERROR >> UPDATE peer SET `version` = ?, `currency` = ?, `status` = ?, `statusTS` = ?, `hash` = ?, `first_down` = ?, `last_try` = ?, `pubkey` = ?, `block` = ?, `signature` = ?, `endpoints` = ?, `raw` = ? WHERE `pubkey` = ? [2,"test_net","DOWN",1465558217,"D1CA26FBD2B88F075D658DDCD815AF355EB1247347F40356C1EF1E48797B73E5",1465824648798,1466235972332,"9eCTWEsrKiW5ityb5h6xM2qKb8GuFkajDzbJbzeFxUEq","13191-000006A9FC4D2F670F4AC8A4F19A63C68A44CE0FBA536B66662056D4AA323567","urU7cUUXJKpDmdhdbKBetr6VqjmsIONARKnFl3GDmsl12yxQRvPZl6NX7e8AIEp164IKQXTAzgG3jrgQVFRUCQ==","[\"BASIC_MERKLED_API win-dev.cgeek.fr 88.174.120.187 9338\"]","Version: 2\nType: Peer\nCurrency: test_net\nPublicKey: 9eCTWEsrKiW5ityb5h6xM2qKb8GuFkajDzbJbzeFxUEq\nBlock: 13191-000006A9FC4D2F670F4AC8A4F19A63C68A44CE0FBA536B66662056D4AA323567\nEndpoints:\nBASIC_MERKLED_API win-dev.cgeek.fr 88.174.120.187 9338\n","9eCTWEsrKiW5ityb5h6xM2qKb8GuFkajDzbJbzeFxUEq"] Error: SQLITE_READONLY: attempt to write a readonly database
    at Error (native)

```

**Comment by c-geek** [comment] 2016-11-04 10:09
Has it happened again? Do you remember the last time you saw this error?

**Comment by c-geek** [comment] 2017-01-02 22:09
I close it for non-reproduction on my side.

However, I really think this occurs because 2 Duniter instances are run simultaneously, or because one instance is running and the duniter command is used concurrently.

**Closed by c-geek** 2017-01-02 22:09 UTC
Labels: bug
