### ISSUE TITLE
Duniter desktop don't start this morning

### ISSUE THREAD

**Issue by galuel** [duniter/duniter#449] opened 2016-05-24 06:09 UTC
Yesterday it was functioning. Now this morning launching it again, it seems to begin to synchronize (not clear, but I can see the number of blocks increasing, should be better to add a progression bar adding "synchronizing" I think), but then it collpases (window suddenly closed).

I join the log file I found in .config/duniter/duniter_default.
[duniter.log.zip](https://github.com/duniter/duniter/files/278879/duniter.log.zip)

**Comment by c-geek** [comment] 2016-05-24 07:50
Duplicate of #413 

However I let this one open because of the "synchronization bar" suggestion.

**Comment by c-geek** [comment] 2016-05-24 16:31
You can download the [latest release alpha66](https://github.com/duniter/duniter/releases), install it, start it, and watch it working wonderfully.

**Closed** 2016-05-24 16:38 UTC
Labels: enhancement
