### ISSUE TITLE
Node is stuck

### ISSUE THREAD

**Issue by Insoleet** [duniter/duniter#415] opened 2016-05-06 17:03 UTC
My node is stuck, on its own block. The logs show this error repeated a lot. Actually, the error was repeated so often that all my log files only contain these lines...

```
2016-05-06T19:01:26+02:00 - warn: Waiting 0s before starting computing next block...
2016-05-06T19:01:26+02:00 - error:  TypeError: Cannot read property 'powMin' of undefined
    at /opt/testnet/.duniter/app/lib/rules/global_rules.js:740:24
    at next (native)
    at onFulfilled (/opt/testnet/.duniter/node_modules/co/index.js:65:19)
    at process._tickCallback (node.js:412:9)
```

**Comment by c-geek** [comment] 2016-05-18 09:41
This is most probably a duplicate of #431.

**Closed by c-geek** 2016-05-18 09:41 UTC
Labels: bug
