### ISSUE TITLE
TypeError: err.indexOf is not a function

### ISSUE THREAD

**Issue by RavanH** [duniter/duniter#616] opened 2016-09-27 19:54 UTC
When syncing from command line `duniter sync cgeek.fr 9330` on Raspberry Pi 3 with Duniter 0.31.0b13 and Node.js 4.5.0, this error appeared in the log:

```bash
2016-09-27T16:57:21+00:00 - ^[[32minfo^[[39m: Try with 88.174.120.187:9330 HnFcSm
2016-09-27T16:57:21+00:00 - ^[[32minfo^[[39m: Sync started.
2016-09-27T16:57:21+00:00 - ^[[32minfo^[[39m: Getting remote blockchain info...
2016-09-27T16:57:21+00:00 - ^[[32minfo^[[39m: Downloading Blockchain...
2016-09-27T16:57:22+00:00 - ^[[31merror^[[39m: TypeError: err.indexOf is not a function
    at /opt/duniter/sources/app/lib/sync.js:334:17
    at throw (native)
    at onRejected (/opt/duniter/sources/node_modules/co/index.js:81:24)
    at _rejected (/opt/duniter/sources/node_modules/q/q.js:804:24)
    at /opt/duniter/sources/node_modules/q/q.js:830:30
    at Promise.when (/opt/duniter/sources/node_modules/q/q.js:1064:31)
    at Promise.promise.promiseDispatch (/opt/duniter/sources/node_modules/q/q.js:748:41)
    at /opt/duniter/sources/node_modules/q/q.js:564:44
    at flush (/opt/duniter/sources/node_modules/q/q.js:110:17)
    at _combinedTickCallback (node.js:376:9)
    at process._tickCallback (node.js:407:11)
```

**Comment by M5oul** [comment] 2016-09-27 19:59
It seems it's just a typo issue as the function doesn't exist.
@c-geek, If it's more complicated, I will let you move this ticket to next milestones.

**Comment by RavanH** [comment] 2016-09-27 22:37
I see `uerr.message` at https://github.com/RavanH/duniter/blob/master/app/lib/sync.js#L288 ... should that be `err.message` ?

**Comment by M5oul** [comment] 2016-09-27 22:56
Surely. You could try and send a pull request.

**Comment by c-geek** [comment] 2016-09-28 06:45
There is no typo, so @RavanH correction won't fix the problem. However it seems `err` is not always a string, so there is not always an `indexOf` method on it. That's why you have the issue.

**Comment by c-geek** [comment] 2016-09-28 06:47
Note: I let you guys fix this one the best way you can!

**Comment by c-geek** [comment] 2016-09-28 06:53
Also, if you [make a search about `NEWER_PEER_DOCUMENT_AVAILABLE`](https://github.com/duniter/duniter/search?utf8=%E2%9C%93&q=NEWER_PEER_DOCUMENT_AVAILABLE) you will see that it does have a `uerr` field, so the problem is necessary elsewhere.

**Comment by RavanH** [comment] 2016-09-28 14:49
Then adding `typeof(err) !== 'undefined' &&` at the start of the if arguments? Or maybe it just needs to be  err.message.indexOf(...) ?

**Comment by c-geek** [comment] 2016-09-28 14:59
Well, `typeof(err) !== 'undefined' &&` won't help since here, `err` is defined. It simply does not have the `indexOf` method because it is not a String but a more complex Object for sure.

So using `typeof(err.indexOf) !== 'undefined' &&` should fix the problem. You can try it directly on your node to verify, by editing the JS source code.

**Comment by RavanH** [comment] 2016-09-28 15:03
Will do :) ... however, I cannot seem to reproduce this error since I restarted with a `duniter reset data`

**Comment by c-geek** [comment] 2016-09-28 15:15
For the coming RML8, I will start to isolate more and more each piece of code into a specific module with a dedicated Unit Test file so this kind of error can be tracked or just mocked, which would allow your new code could be tested right on writing.

It is not only a good pratice, I think it also makes easier for contributors to dive into the code by running just a single piece of the whole software, test it and why not, improve it!

**Comment by c-geek** [comment] 2016-09-28 17:21
OK sorry, I will fix this one by myself because I want to make a release soon with some corrections.

**Closed by c-geek** 2016-09-28 17:21 UTC
Labels: bug, Sync
