### ISSUE TITLE
Cannot switch to the main branch

### ISSUE THREAD

**Issue by galuel** [duniter/duniter#695] opened 2016-11-09 10:09 UTC
I can see my node in Cesium 3.5 associated with Duniter, but not in external 0.4.8 Cesium neither in Sakia

![capture](https://cloud.githubusercontent.com/assets/5245398/20134766/f3bd0f26-a66c-11e6-97d0-81d4f521fc12.png)

**Comment by M5oul** [comment] 2016-11-09 10:37
The IPv4 part seems good but I can't reach the node at this address.
Could you provide logs?
May be UPnP didn't works fine and didn't opened the port.

**Comment by c-geek** [comment] 2016-11-09 12:33
I've made a test this morning, the node was reachable. So it's not a configuration problem. Yet, the node was considered down from the network.

This is possible with nodes that are not run every day, because the network will check less and less frequently if the node is UP and runnning. So it's the node's role to alert the network it is now UP and running. Which it does every 20 minutes approximately.

But maybe the node wasn't very synced with the network, which causes its alert (a Peer document) to be invalid, hence the network still do not see the node.

From the lasts logs I had, your node would have been checked again in 24h (from 2016-11-09 10:30 am) by my node. It could be earlier for other nodes.

**A possible immediate solution: go Settings > Data > Reset** and synchronize again. Otherwise, you can let your node run several hours, and see if it finally shows up in Sakia.

**Comment by c-geek** [comment] 2016-11-09 12:41
The node is reachable right now: http://88.190.82.70:15298/blockchain/current

We can see it is at block 52323, while the network is 53626. It confirms my analysis about the rejected Peer document.

Now, I don't know why the node don't sync with the main branch. You can some logs with us using **Settings > Logs > Create a web link to your logs**. And share it here.

**Comment by galuel** [comment] 2016-11-09 12:47
http://hastebin.com/aqatajozem

**Comment by c-geek** [comment] 2016-11-09 12:51
OK, the error is clear: your node refuses the main blockchain:

    Error: Issuer is not a member

Could you make a backup of your data using: **Settings > Backup > Create a backup** and host it on https://framadrop.org/ ? Then please share the link here.

**Comment by galuel** [comment] 2016-11-09 12:57
https://framadrop.org/r/Uz4D8kVkrv#7Muxl+sR977BbrTIJmQg7K00zMB9Op/Nsktu0HYrQIY=

**Comment by c-geek** [comment] 2016-11-12 11:40
I've made a lot of tests on this issue, commited some code which does not seem directly connected, yet I no more reproduce the issue.

> Note to myself: test again with the old code to figure out what was the cause.

**Comment by M5oul** [comment] 2016-11-12 23:41
I think, I am also experimenting issue for my nodes to join main branch.

**Comment by c-geek** [comment] 2016-11-13 09:00
@M5oul could you make a bakcup also? I could analyze it.

**Comment by M5oul** [comment] 2016-11-13 09:08
- [Backup](https://moul.re/jirafeau/f.php?h=2aI15CS4&d=1)

**Comment by c-geek** [comment] 2016-11-13 09:21
Good :-) Could you let it available for 2-3 days? I currently have a very low Internet connection and can't download it.

**Comment by M5oul** [comment] 2016-11-13 09:25
Yep, [here is a new one](https://moul.re/jirafeau/f.php?h=2A9HiCUb&d=1) always available.

**Comment by c-geek** [comment] 2016-11-14 12:46
Do you remember from when do you have this behavior? Is it from 0.50.0 or 0.50.1a1?

**Comment by c-geek** [comment] 2016-11-14 12:55
I reproduced your issue using HEAD version of duniter on `dev` branch, which is 0.50.0a3 (very similar version to 0.50.0a1, which brought some changes in the rules appliance), but not with 0.50.0.

**Comment by M5oul** [comment] 2016-11-14 13:02
I think it appears from v0.50.0.

I don't remember very well and I am not sure about following statement or if it's the cause of this bug:
- It happen on my ARM board when it was disconnected from test-net network all night (Internet connection issue).
- On the morning, I discovered the node was alone on it's branch.
- I solves the Internet connection and the node won't join back main branch which had much more than required conditions to do it.
- I couldn't revert blocks. Blocks from it's branch was reverted but, as resync it was unfortunately still joining same branch :grimacing: 
- I finally, reset db and sync.

**Comment by c-geek** [comment] 2016-11-14 14:03
OK, what I can say now is: from commit c020fe3e077a3d56116cfcbe332e6008eb1969f6, I not reproduce any bug with your backup.

And I do not reproduce anything either with 0.50.0.

Maybe a hint: the problem I had with your backup ("Wrong MedianTime") can occur if your `conf.json` file was modified, in its currency parameters fields. That's the only thing I could reproduce, at commit 00ffd2c503fcbcfeaf4491623bb0428187aedcc0, and fixed the bug at commit c020fe3e077a3d56116cfcbe332e6008eb1969f6.

I don't know if this was the error you had.

**Comment by c-geek** [comment] 2016-11-14 15:10
OK I give up for now, I change the milestone to horizon. I guess we need a cleaner code to understand what really goes on.

We'll see this later, we already have improvements.

**Comment by c-geek** [comment] 2016-12-02 10:12
The error:

    Error: Issuer is not a member

occurs again. I don't it's origin yet, but for sure it is fork related.

**Comment by c-geek** [comment] 2017-01-02 21:59
Should be fixed in v0.80, planned for the coming days.

**Comment by c-geek** [comment] 2017-01-02 22:00
Linked to #683

**Closed by c-geek** 2017-01-02 21:59 UTC
Labels: bug, network
