### ISSUE TITLE
Update nan module to handle Nodejs v6

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#496] opened 2016-07-04 17:08 UTC
Every commands result in JS/C stack traces.
Testing `organization` branch with Node 6.2, I get many JS/C stack traces for every commands:
- [Logs](https://moul.re/zerobin/?db2169092d18478b#td5PNVxEadva2ZwRWjnlbxrzIpTUddpFAEarl3Q13Oo=)

**Comment by c-geek** [comment] 2016-07-04 18:49
This is probably linked to [nan](https://github.com/nodejs/nan) version, not compliant with Nodejs v6 yet. We need to upgrade on addon modules like naclb or wotb.

**Comment by M5oul** [comment] 2016-07-06 14:38
It' seems to be that.
Linked to https://github.com/duniter/duniter/issues/381 to have Duniter working with Node v6.

**Comment by M5oul** [comment] 2016-08-31 00:23
I would like to make Duniter compatible with Node.js v6.

- Could you transfer [NaClb repository](https://github.com/c-geek/naclb) ownership to Duniter organization.
- Explain me how to publish this packages on [npmjs](https://www.npmjs.com).

**Comment by c-geek** [comment] 2016-08-31 09:43
OK, I will do it but first I need to automate the publishing just like Duniter with a `release.sh` script. The manual deployment is just super annoying and not very useful.

**Comment by M5oul** [comment] 2016-08-31 11:22
Ok, it will better.

**Comment by c-geek** [comment] 2016-10-07 11:55
Duplicate of #381, since only sqlite module was blocking the upgrade to Node.js 6

**Closed by c-geek** 2016-10-07 11:55 UTC
Labels: bug, Command line interface
