### ISSUE TITLE
BMA /ws/block > Missing `monetaryMass` (sometimes)

### ISSUE THREAD

**Issue by blavenie** [duniter/duniter#1081] opened 2017-08-21 14:28 UTC
The ES node has registered a block without the field `monetaryMass`...

Is it missing in the code of /ws/block ?

**Comment by blavenie** [comment] 2017-08-21 14:29
see https://github.com/duniter/duniter4j/issues/20

**Comment by c-geek** [comment] 2017-08-21 14:36
Yes, but this is fixed in Duniter 1.5.2 which is coming.

**Comment by c-geek** [comment] 2017-08-21 14:37
Duplicate of #1080.

**Comment by blavenie** [comment] 2017-08-21 14:43
#1080 seems ok for monetaryMass.
But `dividend` missing a `paseInt` : see https://github.com/duniter/duniter/blob/c4ea9a50b167b86728320e19ad184f20d1549685/app/lib/dto/BlockDTO.ts#L208

**Comment by c-geek** [comment] 2017-08-21 15:17
fixed in 1.5.2 also

**Closed** 2017-08-21 15:17 UTC
Labels: BMA api, bug
