### ISSUE TITLE
Current block number is not well refreshed

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#395] opened 2016-04-29 09:54 UTC
It happen with fast block generation.

**Comment by M5oul** [comment] 2016-05-16 09:31
It do not seems to be fixed on my side.

**Comment by c-geek** [comment] 2016-05-16 11:57
Could you give more details? For example, what is the number displayed? Do it evolves some time, or never? Because I do not reproduce your problem.

Also, what packaging do you use? .deb? And what command do you run?

**Comment by M5oul** [comment] 2016-05-16 20:50
The block number from Sakia point of view is up than the one display on Duniter interface.
Yep, I think it evolve sometimes.
I use the tar.gz and I run it with `./nw`.


![capture d ecran de 2016-05-16 22-49-01](https://cloud.githubusercontent.com/assets/4758871/15303514/797c5dd2-1bb8-11e6-85cf-ae879f7ade52.png)

**Comment by c-geek** [comment] 2016-07-29 17:25
Does it still happen to you, @M5oul? Also, I note on this screenshot that you had Network configuration issue which might explain why the number is not correctly updated.

**Comment by M5oul** [comment] 2016-07-29 17:56
I will try it again as soon as I can, if it's still present.
Last time I use desktop build, I still had the issue.
This configuration warning is displayed when my configuration is good.
I tried to do automatic configuration which doesn't works :(

**Comment by c-geek** [comment] 2016-08-05 11:03
I also close this one, maybe it has be fixed as a side effect of code refactoring or correction of another issue.

Again, if you reproduce the issue, please reopen this issue.

**Comment by M5oul** [comment] 2016-08-08 22:10
I could reproduce it:
![capture d ecran de 2016-08-09 00-08-22](https://cloud.githubusercontent.com/assets/4758871/17498094/7fd90370-5dc5-11e6-863a-12433d14f2bd.png)
It's a minor bug, we could move it to an other milestone :wink:

**Comment by c-geek** [comment] 2016-08-09 08:58
Yes, let's put this to "whenever I will have the time to do this" milestone :stuck_out_tongue:

**Comment by M5oul** [comment] 2016-08-09 10:23
Finally, my previous test is wrong.
The node is not retrieving last blocks because of a bad Internet connection.
Sorry for that. I will reopen it if I can reproduce it :wink:

**Comment by M5oul** [comment] 2016-08-10 17:52
Ok, finally, I am sure that it happen again even with desktop and YunoHost versions.

**Comment by c-geek** [comment] 2017-01-02 22:15
Duplicate of #746

**Closed by c-geek** 2017-01-02 22:15 UTC
Labels: enhancement, Graphical interface
