### ISSUE TITLE
FakeNet review by inso

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#786] opened 2017-01-15 12:37 UTC
French comments found on the chatroom.
---------------

1. Lookup issue:
> [04:28:28] <inso_> cgeek : petit bug dans le lookup
> [04:28:29] <inso_> http://fakenet.cgeek.fr:10900/wot/lookup/inso
> [04:28:32] <inso_> pas de block_hash

@Insoleet OK, fixed in fb73ef6b135abe56f8c7b7dc5c8af43898a11f3a.

---------------
2. Revocation not taken into account
> [06:08:16] <inso_> bon j'ai publié la revocation de mon identité sur fakenet, à voir ce qu'il se passe.. :)
> [07:05:32] <inso_> ah tient mon noeud testnet a planté hier... sans log...
> [09:33:18] <cgeek> inso: mon nœud n'a pas reçu la révocation visiblement
> [09:36:03] <inso> pourtant elle semblait être accepté
> [09:36:09] <inso> je regarderai ce soir...

@Insoleet Sakia has raised an error during revocation publication:

    Task exception was never retrieved
	future: <Task finished coro=<accept() done, defined at sakia/gui/dialogs/revocation/controller.py:108> exception=AttributeError("'RevocationModel' object has no attribute '_logger'",)>
	    ----
	    Traceback (most recent call last):
	      File "asyncio/tasks.py", line 239, in _step
	    File "sakia/gui/dialogs/revocation/controller.py", line 117, in accept
	    File "sakia/gui/dialogs/revocation/model.py", line 50, in send_to_node
	    AttributeError: 'RevocationModel' object has no attribute '_logger'
	    
---------------
3. `expiresIn` difference
> [21:01:22] <inso_> cgeek : petit bug sur les expiresIn dans requirements
> [21:01:29] <inso_> deux noeuds ne vont pas répondre la meme chose
> [21:02:15] <inso_> exemple : http://cgeek.fr:9330/wot/requirements/inso
> [21:02:22] <inso_> http://testnet.duniter.inso.ovh/wot/requirements/inso
> [21:02:29] <inso_> j'ai l'impression que ça n'utilise pas le medianTime du coup

@Insoleet I don't see any difference today.

---------------
4. Transactions with more than 100 lines
> [21:53:51] <inso_> pour une transaction avec plus de 100 lignes j'ai l'erreur "Transaction has wrong line ending format"
> [21:54:04] <inso_> Il faudrait pas une autre erreur pour qu'on puisse s'adapter ?

**Comment by Insoleet** [comment] 2017-01-16 10:23
> @Insoleet I don't see any difference today.

There is something, for sure, because the veryfication algorithm sometimes canno't find a valid data because the network does not agree on the time placed in the certifications. Let's see if we reproduce it later.

**Comment by c-geek** [comment] 2017-02-15 15:13
2. Revocation not taken into account

Fixed in #832.

**Comment by Insoleet** [comment] 2017-07-06 19:43
I think we can close it now ;)

**Closed by Insoleet** 2017-07-06 19:43 UTC
